### PR TITLE
Add counters

### PR DESCRIPTION
**Pull request by svenfuchs**
Includes (and depends on) https://github.com/travis-ci/travis-migrations/pull/101

Disregard all commits except https://github.com/travis-ci/travis-migrations/pull/102/commits/29472d2b0e278a2b379c5e5460c6785a6c6f6ee4 and https://github.com/travis-ci/travis-migrations/pull/102/commits/391ed7ff1a6c24e42d1e2c3da0bbe7f5c7b0a818

### CODE REVIEW

**Comment by aakritigupta** [comment]
The counts migration looks fine to me, though I haven't gone through the aggregation code yet.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
we should definitely keep an eye on postgres memory usage / cache hit rate in production. I would also suggest we wait for the postgres upgrade tomorrow (https://github.com/travis-ci/reliability/issues/45) before applying this on org.

as for how we roll it out, the index creations are unlikely to finish while running the migration via migrations, so I would suggest we apply those manually, one by one.

**Comment by drogus** [comment]
One thing that bothers me a bit here is the hardcoded timestamp. I was thinking that maybe we could get rid of it by setting the date of adding the triggers as a session default with [`ALTER DATABASE ... SET ...`](https://www.postgresql.org/docs/9.1/static/sql-alterdatabase.html)?

**Comment by svenfuchs** [comment]
@drogus i completely agree! i've now made it so that at least it would re-interpolate `Time.now` into that timestamp when you run the migration, but that still kinda sucks. when we set the variable per session though, then we need to make sure that whatever application writes data also sets that variable, am i right?

**Comment by svenfuchs** [comment]
Counters have been installed and backfilled on both org and com (`job` on com is close to finishing), so I'm gonna merge this.

**Pull request merged**
