### PR TITLE
Removed the unnecessary dependancies and restructured a bit

### PR DESCRIPTION
**Pull request by renee-travisci**
Things to note:
- This was tested for clean installs (no existing data) on PostgreSQL 9.5.3
- The latest version of AR (4.2.6) expects not null constraints specified on timestamp (created_at, updated_at) columns in the migration. Old migrations that did not have them, had the NOT NULL constraint removed from the columns in structure.sql (sql ruby schema file)
- There is a warning that appears with some rake tasks about 'config.eager_load is set to nil.' it can be ignored.
- Someone should check my work on what should be specified as a development_dependancy vs runtime_dependancy in the gemspec
- If anyone was using the 'rails g migration' command to generate AR migrations that will no longer work w/o rails (the instructions in the README don't use it so I figured this was ok)
- I do not see any seed data and there is no schema.rb file, so I've changed the instructions from rake db:setup to rake db:create as that was the only thing that command was actually doing

### CODE REVIEW

**Comment by renee-travisci** [comment]
@carlad @svenfuchs I can add an rspec test that calls drop, create, and migrate to ensure that those run cleanly if we want to add at least 1 test for this gem.

**Comment by carlad** [comment]
That would be great Renee, thanks :-)



On Thu, May 19, 2016 at 2:06 PM, Renée Hendricksen <notifications@github.com
> wrote:

> @carlad <https://github.com/carlad> @svenfuchs
> <https://github.com/svenfuchs> I can add an rspec test that calls drop,
> create, and migrate to ensure that those run cleanly if we want to add at
> least 1 test for this gem.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-migrations/pull/15#issuecomment-220304974>
>



-- 




Carla Drago

software developer
carla@travis-ci.com <justine@travis-ci.com>

*Travis CI*   Test and Deploy with Confidence.
www.travis-ci.com

*Travis CI GmbH*, Rigaer Str.8, 10247 Berlin, Germany | *GF/CEO:* Mathias
Meyer, Joshua Kalderimis | *Contact:* contact@travis-ci.org
<contact@travis-ci.com>
Amtsgericht Charlottenburg, Berlin, HRB 140133 B | Umsatzsteuer-ID gemäß
§27 a Umsatzsteuergesetz: DE282002648

**Comment by svenfuchs** [comment]
reviewed this with @renee-travisci and we believe this can be merged once we've changed the gemspec to use development dependencies (so travis-migrations does not force specific versions on apps)

@carlad wdyt?

**Comment by carlad** [comment]
This looks great. I just talked to Renee about adding the NOT NULL constraint into the migrations files for where this latest version of Active Record has removed it from with structure.sql, which I agree we should do.

**Comment by renee-travisci** [comment]
This is good to go. I added a travis.yml file and added the hook for the new tests. I also bumped the version so apps using this will need to be updated to use the new version.

**Comment by svenfuchs** [comment]
@renee-travisci super work 👍  

Shall we merge this even though the (newly added) Travis CI builds fail? We could easily make this a new issue.

Two notes:

* I believe this [monkeypatch](https://github.com/travis-ci/travis-migrations/blob/1b69cf30e5c8239919daf210589011e5320faf91/Rakefile#L18) was there to add `disable_ddl_transaction` to an older version of ActiveRecord that had been used in various applications. Since we now moved all migrations to here (travis-migration), and applications aren't supposed to run migrations locally (inside their root dir) any more, ... we can pick whatever AR version we like for running the migrations. So I believe we should be able to remove the monkeypatch.

* I believe the specs fail because `9.5` is not pre-installed on the Docker image. We use `9.3.6` in production on org, and `9.3.10` in production on com at the moment. Heroku has `9.5`, but the dbs would have to be upgraded, and I'm not sure when that is going to happen. Maybe we could run the tests against whatever versions `9.3.x` and/or `9.4.x` Travis CI has preinstalled on the Docker images?

**Comment by renee-travisci** [comment]
@svenfuchs @carlad I think this is good to go. I think we should make some tickets to discuss taking the rake tasks out of other repositories related to this gem / db access and squashing the old migrations.

**Comment by svenfuchs** [comment]
@renee-travisci super, thanks for taking care of this. would you like to open new issues for the other discussions? i can also do that if you'd prefer that.

**Pull request merged**
