### PR TITLE
Update db/structure.sql

### PR DESCRIPTION
**Pull request by BanzaiMan**
Corresponds to the previous commit

### CODE REVIEW

**Comment by BanzaiMan** [comment]
@carlad Could you review this? I don't think it is necessary to run this migration on production systems, but I'd leave that decision to you.

**Comment by carlad** [comment]
@BanzaiMan So am I correct in understanding that the change here is to align the structure.sql with correct timestamp values? The description isn't very clear.

The aim with the databases is that both staging and production databases have the same structure. 
Additionally there is only one branch (master) that migrations are run from. So it's not clear to me how there would be a different structure on staging vs production.

**Comment by BanzaiMan** [comment]
@carlad I apologize if the purpose of this PR wasn't clear.

This PR is not so much about the existing shared databases in use, but for local development.

At @59bb988, we cannot set it up.

```sh-session
$ git remote -v
origin  git@github.com:travis-ci/travis-migrations.git (fetch)
origin  git@github.com:travis-ci/travis-migrations.git (push)
production      git@heroku.com:travis-production.git (fetch)
production      git@heroku.com:travis-production.git (push)
staging git@heroku.com:travis-staging.git (fetch)
staging git@heroku.com:travis-staging.git (push)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git log -1
commit 59bb9881c621316a75b3dda21d8445a1d781716a
Merge: a2bb07d d2505dd
Author: Hiro Asari <asari.ruby@gmail.com>
Date:   Thu Apr 14 12:23:26 2016 -1000

    Merge pull request #12 from travis-ci/ha-bug-fix-migration-versions

    Move DB versions so that they are run in order
$ bundle exec rake db:drop
$ bundle exec rake db:setup
You have 2 pending migrations:
  20160412113020 BuildsDropIndexOwnerType
  20160412113070 RepositoriesDropIndexLastBuildStartedAt
Run `rake db:migrate` to update your database then try again.
$ bundle exec rake db:migrate
==  BuildsDropIndexOwnerType: migrating =======================================
-- execute("DROP INDEX CONCURRENTLY index_builds_on_owner_type")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  index "index_builds_on_owner_type" does not exist
: DROP INDEX CONCURRENTLY index_builds_on_owner_type/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:466:in `block in method_missing'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `block in say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:458:in `method_missing'
/Users/asari/Development/src/travis-ci/travis-migrations/db/migrate/20160412113020_builds_drop_index_owner_type.rb:5:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:389:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:528:in `migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:75:in `block (2 levels) in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `call'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `ddl_transaction'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:74:in `block in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `each'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:570:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:551:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  index "index_builds_on_owner_type" does not exist
: DROP INDEX CONCURRENTLY index_builds_on_owner_type
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:466:in `block in method_missing'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `block in say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:458:in `method_missing'
/Users/asari/Development/src/travis-ci/travis-migrations/db/migrate/20160412113020_builds_drop_index_owner_type.rb:5:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:389:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:528:in `migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:75:in `block (2 levels) in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `call'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `ddl_transaction'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:74:in `block in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `each'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:570:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:551:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
PG::UndefinedObject: ERROR:  index "index_builds_on_owner_type" does not exist
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:466:in `block in method_missing'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `block in say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `say_with_time'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:458:in `method_missing'
/Users/asari/Development/src/travis-ci/travis-migrations/db/migrate/20160412113020_builds_drop_index_owner_type.rb:5:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:410:in `block in migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:389:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:528:in `migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:75:in `block (2 levels) in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `call'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:35:in `ddl_transaction'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:74:in `block in migrate'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `each'
/Users/asari/Development/src/travis-ci/travis-migrations/Rakefile:55:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:570:in `up'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/migration.rb:551:in `migrate'
/Users/asari/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/asari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
$ bundle exec rake db:migrate:status

database: travis_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20101126174706  Create repositories
   up     20101126174715  Create builds
⋮
   up     20151127154600  Broadcasts add index recipient id and recipient type
   up     20151202122200  Users add first logged in at
   up     20160107120927  Add cron table
   up     20160303165750  Add debug options to jobs
  down    20160412113020  Builds drop index owner type
   up     201604121130200  ********** NO FILE **********
  down    20160412113070  Repositories drop index last build started at
   up     201604121130700  ********** NO FILE **********
   up     20160412121405  Jobs drop index type
   up     20160412123900  Jobs drop index source type
   up     20160414214442  Jobs add index queued at
```

Notice the migrations with bad version numbers.

With this PR, all is well.

```sh-session
$ git checkout ha-bug-fix-migration-versions
Switched to branch 'ha-bug-fix-migration-versions'
$ git log -1
commit 541dce1a942e31e501107377adcc3fb6f33e1f04
Author: Hiro Asari <asari.ruby@gmail.com>
Date:   Tue Apr 19 03:07:08 2016 -1000

    Update db/structure.sql
    
    Corresponds to the previous commit
$ bundle exec rake db:drop
$ bundle exec rake db:setup
$ bundle exec rake db:migrate:status

database: travis_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20101126174706  Create repositories
   up     20101126174715  Create builds
⋮
   up     20150923131400  Broadcasts add category
   up     20151112153500  Create stars
   up     20151113111400  Stars add index user id and repository
   up     20151127153500  Users add index github oauth token
   up     20151127154200  Annotations add index job
   up     20151127154600  Broadcasts add index recipient id and recipient type
   up     20151202122200  Users add first logged in at
   up     20160107120927  Add cron table
   up     20160303165750  Add debug options to jobs
   up     20160412113020  Builds drop index owner type
   up     20160412113070  Repositories drop index last build started at
   up     20160412121405  Jobs drop index type
   up     20160412123900  Jobs drop index source type
   up     20160414214442  Jobs add index queued at
```

**Comment by BanzaiMan** [comment]
Actually, the production DB exhibits the first behavior with respect to migrations:

```
  down    20160412113020  Builds drop index owner type
   up     201604121130200  ********** NO FILE **********
  down    20160412113070  Repositories drop index last build started at
   up     201604121130700  ********** NO FILE **********
```

Not sure what the best course of action is.

**Comment by BanzaiMan** [comment]
Hmm. I might be better to revert the previous commit (which renamed migration files) instead.

**Comment by carlad** [comment]
Okay. Have talked to @svenfuchs and we think we should merge this PR, and then I can update the timestamps manually on the databases. Will let you know once this is done, okay?

**Comment by BanzaiMan** [comment]
@carlad Thanks for the followup!

**Comment by carlad** [comment]
I've updated all the databases and run the migrations. The new index for jobs_on_queued_at on jobs has been added to all environments.

**Pull request merged**
